import type { Message, Quote, Moment, Recommendation, Topic, Activity, MessageFolder, MessageFolderItem, CollagePhoto, MessageNote, Nightmare, Ick, Poem, QuoteCategory } from "@/lib/types/database";

export const MOCK_MESSAGES: Message[] = [
  // March 13
  {
    id: "m1",
    from_user: "chloe",
    type: "text",
    text: "Hey, I just finished that book you recommended. It was so good!",
    voice_url: null,
    media_url: null,
    duration: null,
    status: "read",
    is_pinned: true,
    pinned_at: "2026-03-13T21:00:00Z",
    pinned_by: "michael",
    created_at: "2026-03-13T14:20:00Z",
  },
  {
    id: "m2",
    from_user: "michael",
    type: "text",
    text: "The Song of Achilles?? I knew you'd love it 😊",
    voice_url: null,
    media_url: null,
    duration: null,
    status: "read",
    is_pinned: false,
    pinned_at: null,
    pinned_by: null,
    created_at: "2026-03-13T14:22:00Z",
  },
  {
    id: "m3",
    from_user: "chloe",
    type: "text",
    text: "I literally cried at the end. We need to watch the movie when it comes out",
    voice_url: null,
    media_url: null,
    duration: null,
    status: "read",
    is_pinned: false,
    pinned_at: null,
    pinned_by: null,
    created_at: "2026-03-13T14:24:00Z",
  },
  // March 14
  {
    id: "m4",
    from_user: "michael",
    type: "text",
    text: "Good night baby, dream about me 🌙",
    voice_url: null,
    media_url: null,
    duration: null,
    status: "read",
    is_pinned: false,
    pinned_at: null,
    pinned_by: null,
    created_at: "2026-03-14T23:30:00Z",
  },
  {
    id: "m5",
    from_user: "chloe",
    type: "voice",
    text: null,
    voice_url: "/mock-voice.webm",
    media_url: null,
    duration: 8,
    status: "read",
    is_pinned: true,
    pinned_at: "2026-03-14T23:45:00Z",
    pinned_by: "michael",
    created_at: "2026-03-14T23:35:00Z",
  },
  {
    id: "m6",
    from_user: "chloe",
    type: "text",
    text: "Good night my love, always dreaming about you 💛",
    voice_url: null,
    media_url: null,
    duration: null,
    status: "read",
    is_pinned: false,
    pinned_at: null,
    pinned_by: null,
    created_at: "2026-03-14T23:36:00Z",
  },
  // March 15 (Today)
  {
    id: "m7",
    from_user: "michael",
    type: "text",
    text: "Good morning beautiful 💛",
    voice_url: null,
    media_url: null,
    duration: null,
    status: "read",
    is_pinned: false,
    pinned_at: null,
    pinned_by: null,
    created_at: "2026-03-15T08:00:00Z",
  },
  {
    id: "m8",
    from_user: "chloe",
    type: "text",
    text: "Good morning!! I miss you so much 🥺",
    voice_url: null,
    media_url: null,
    duration: null,
    status: "read",
    is_pinned: false,
    pinned_at: null,
    pinned_by: null,
    created_at: "2026-03-15T08:02:00Z",
  },
  {
    id: "m9",
    from_user: "michael",
    type: "text",
    text: "I miss you too. Only 12 more days!",
    voice_url: null,
    media_url: null,
    duration: null,
    status: "read",
    is_pinned: false,
    pinned_at: null,
    pinned_by: null,
    created_at: "2026-03-15T08:03:00Z",
  },
  {
    id: "m10",
    from_user: "chloe",
    type: "text",
    text: "I can't wait 😭 What are you up to today?",
    voice_url: null,
    media_url: null,
    duration: null,
    status: "read",
    is_pinned: false,
    pinned_at: null,
    pinned_by: null,
    created_at: "2026-03-15T08:05:00Z",
  },
  {
    id: "m11",
    from_user: "michael",
    type: "voice",
    text: null,
    voice_url: "/mock-voice.webm",
    media_url: null,
    duration: 12,
    status: "delivered",
    is_pinned: false,
    pinned_at: null,
    pinned_by: null,
    created_at: "2026-03-15T08:07:00Z",
  },
  {
    id: "m12",
    from_user: "chloe",
    type: "text",
    text: "Aww that's so sweet, send me more voice notes 🥰",
    voice_url: null,
    media_url: null,
    duration: null,
    status: "sent",
    is_pinned: false,
    pinned_at: null,
    pinned_by: null,
    created_at: "2026-03-15T08:09:00Z",
  },
  {
    id: "m13",
    from_user: "michael",
    type: "image",
    text: null,
    voice_url: null,
    media_url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='240' height='180'%3E%3Cdefs%3E%3ClinearGradient id='img1' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3E%3Cstop offset='0%25' stop-color='%23667eea'/%3E%3Cstop offset='100%25' stop-color='%23764ba2'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='240' height='180' fill='url(%23img1)'/%3E%3Ctext x='120' y='95' text-anchor='middle' fill='white' font-size='14' font-family='sans-serif'%3EPhoto from walk%3C/text%3E%3C/svg%3E",
    duration: null,
    status: "sent",
    is_pinned: false,
    pinned_at: null,
    pinned_by: null,
    created_at: "2026-03-15T08:12:00Z",
  },
  {
    id: "m14",
    from_user: "chloe",
    type: "gif",
    text: null,
    voice_url: null,
    media_url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='240' height='160'%3E%3Cdefs%3E%3ClinearGradient id='gif1' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3E%3Cstop offset='0%25' stop-color='%23f093fb'/%3E%3Cstop offset='100%25' stop-color='%23f5576c'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='240' height='160' fill='url(%23gif1)'/%3E%3Ctext x='120' y='85' text-anchor='middle' fill='white' font-size='16' font-family='sans-serif'%3EGIF%3C/text%3E%3C/svg%3E",
    duration: null,
    status: "sent",
    is_pinned: false,
    pinned_at: null,
    pinned_by: null,
    created_at: "2026-03-15T08:13:00Z",
  },
];

export const MOCK_FOLDERS: MessageFolder[] = [
  {
    id: "f1",
    name: "Important",
    emoji: "⭐",
    created_by: "michael",
    created_at: "2026-03-10T00:00:00Z",
  },
  {
    id: "f2",
    name: "Funny",
    emoji: "😂",
    created_by: "chloe",
    created_at: "2026-03-11T00:00:00Z",
  },
  {
    id: "f3",
    name: "Voice Notes",
    emoji: "🎙️",
    created_by: "michael",
    created_at: "2026-03-12T00:00:00Z",
  },
];

export const MOCK_FOLDER_ITEMS: MessageFolderItem[] = [
  {
    id: "fi1",
    folder_id: "f1",
    message_id: "m1",
    added_by: "michael",
    added_at: "2026-03-13T21:00:00Z",
  },
  {
    id: "fi2",
    folder_id: "f3",
    message_id: "m5",
    added_by: "michael",
    added_at: "2026-03-14T23:45:00Z",
  },
  {
    id: "fi3",
    folder_id: "f3",
    message_id: "m11",
    added_by: "michael",
    added_at: "2026-03-15T08:10:00Z",
  },
];

export const MOCK_QUOTE_CATEGORIES: QuoteCategory[] = [
  { id: "qc1", value: "racist", label: "Racist Quote of the Month", emoji: "😬", created_at: "2026-01-01T00:00:00Z" },
  { id: "qc2", value: "out_of_context", label: "Out of Context", emoji: "🤨", created_at: "2026-01-01T00:00:00Z" },
  { id: "qc3", value: "libtard", label: "Libtard Quote of the Month", emoji: "🗳️", created_at: "2026-01-01T00:00:00Z" },
];

export const MOCK_QUOTES: Quote[] = [
  {
    id: "1",
    text: "I'm not racist, but...",
    author: "Uncle Dave",
    category: "racist",
    month: "March 2026",
    added_by: "michael",
    created_at: "2026-03-05T00:00:00Z",
  },
  {
    id: "2",
    text: "I just think it's interesting that...",
    author: "Grandma",
    category: "racist",
    month: "March 2026",
    added_by: "chloe",
    created_at: "2026-03-08T00:00:00Z",
  },
  {
    id: "3",
    text: "I need you to come over and help me with my pipe",
    author: "Dad",
    category: "out_of_context",
    month: "March 2026",
    added_by: "michael",
    created_at: "2026-03-10T00:00:00Z",
  },
  {
    id: "4",
    text: "Well actually the electoral college exists for a reason",
    author: "That guy at the party",
    category: "libtard",
    month: "February 2026",
    added_by: "chloe",
    created_at: "2026-02-15T00:00:00Z",
  },
];

export const MOCK_MOMENTS: Moment[] = [
  {
    id: "1",
    title: "First Video Call",
    date: "2025-06-15",
    emoji: "📹",
    description: "We talked for 4 hours and didn't want to hang up",
    added_by: "michael",
    created_at: "2025-06-16T00:00:00Z",
  },
  {
    id: "2",
    title: "Said I Love You",
    date: "2025-09-20",
    emoji: "❤️",
    description: "Under the stars, even through a screen",
    added_by: "chloe",
    created_at: "2025-09-21T00:00:00Z",
  },
  {
    id: "3",
    title: "First Visit",
    date: "2025-12-20",
    emoji: "✈️",
    description: "The airport hug that lasted forever",
    added_by: "michael",
    created_at: "2025-12-21T00:00:00Z",
  },
];

export const MOCK_RECOMMENDATIONS: Recommendation[] = [
  {
    id: "1",
    title: "Past Lives",
    category: "movie",
    from_user: "michael",
    emoji: "🎬",
    done: true,
    link: null,
    created_at: "2026-01-10T00:00:00Z",
  },
  {
    id: "2",
    title: "Normal People",
    category: "show",
    from_user: "chloe",
    emoji: "📺",
    done: false,
    link: "https://www.netflix.com",
    created_at: "2026-02-05T00:00:00Z",
  },
  {
    id: "3",
    title: "The Song of Achilles",
    category: "book",
    from_user: "chloe",
    emoji: "📚",
    done: false,
    link: null,
    created_at: "2026-02-14T00:00:00Z",
  },
  {
    id: "4",
    title: "Lover - Taylor Swift",
    category: "song",
    from_user: "michael",
    emoji: "🎵",
    done: true,
    link: "https://open.spotify.com",
    created_at: "2026-01-20T00:00:00Z",
  },
  {
    id: "5",
    title: "Where Should We Begin?",
    category: "podcast",
    from_user: "chloe",
    emoji: "🎙️",
    done: false,
    link: null,
    created_at: "2026-03-01T00:00:00Z",
  },
];

export const MOCK_TOPICS: Topic[] = [
  {
    id: "1",
    text: "If we could live anywhere in the world together, where would it be?",
    used: false,
    added_by: "michael",
    created_at: "2026-03-10T00:00:00Z",
  },
  {
    id: "2",
    text: "What's a childhood memory that shaped who you are?",
    used: false,
    added_by: "chloe",
    created_at: "2026-03-08T00:00:00Z",
  },
  {
    id: "3",
    text: "Dream date night when we're finally together?",
    used: true,
    added_by: "michael",
    created_at: "2026-02-28T00:00:00Z",
  },
  {
    id: "4",
    text: "What are we most grateful for about each other?",
    used: true,
    added_by: "chloe",
    created_at: "2026-02-20T00:00:00Z",
  },
];

export const MOCK_MESSAGE_NOTES: MessageNote[] = [
  {
    id: "mn1",
    message_id: "m5",
    text: "She said she loves the way I laugh",
    added_by: "michael",
    created_at: "2026-03-14T23:40:00Z",
  },
  {
    id: "mn2",
    message_id: "m5",
    text: "Mentioned wanting to visit in April",
    added_by: "michael",
    created_at: "2026-03-14T23:41:00Z",
  },
];

export const MOCK_POEMS: Poem[] = [
  {
    id: "poem1",
    title: "Morning Coffee",
    text: "There once was a girl who loved lattes,\nWhose mornings were chronically splatty,\nShe'd grumble and groan,\nIn a caffeinated tone,\nTill the oat milk made everything happy.",
    type: "limerick",
    from_user: "michael",
    to_user: "chloe",
    date: "2026-03-14",
    created_at: "2026-03-14T00:00:00Z",
  },
  {
    id: "poem2",
    title: "The Snorer",
    text: "You say you don't snore\nbut the walls disagree,\na symphony of chaos\nperformed just for me.",
    type: "free_verse",
    from_user: "chloe",
    to_user: "michael",
    date: "2026-02-28",
    created_at: "2026-02-28T00:00:00Z",
  },
  {
    id: "poem3",
    title: "Grocery Run",
    text: "A couple went shopping one day,\nHe grabbed chips and she said no way,\nThey argued in aisle three,\nOver organic broccoli,\nAnd left with just bread anyway.",
    type: "limerick",
    from_user: "chloe",
    to_user: "michael",
    date: "2026-02-14",
    created_at: "2026-02-14T00:00:00Z",
  },
  {
    id: "poem4",
    title: "Sunday",
    text: "Tangled sheets and sleepy eyes,\nNowhere to be, no alarms to rise,\nYour laugh beside me,\nSoft and free,\nThis is all I need.",
    type: "free_verse",
    from_user: "michael",
    to_user: "chloe",
    date: "2026-01-20",
    created_at: "2026-01-20T00:00:00Z",
  },
  {
    id: "poem5",
    title: "The Remote",
    text: "There once was a battle so dire,\nOver who held the remote by the fire,\nShe wanted her shows,\nHe wanted his prose,\nSo they compromised — and watched The Wire.",
    type: "limerick",
    from_user: "michael",
    to_user: "chloe",
    date: "2025-12-25",
    created_at: "2025-12-25T00:00:00Z",
  },
];

export const MOCK_ICKS: Ick[] = [
  {
    id: "ick1",
    text: "Playing with Legos past the age of 12",
    about: "michael",
    added_by: "chloe",
    created_at: "2026-03-10T00:00:00Z",
  },
  {
    id: "ick2",
    text: "Wearing those toe shoes to the gym",
    about: "michael",
    added_by: "chloe",
    created_at: "2026-03-08T00:00:00Z",
  },
  {
    id: "ick3",
    text: "Narrating their own cooking like a YouTube video",
    about: "michael",
    added_by: "chloe",
    created_at: "2026-03-05T00:00:00Z",
  },
  {
    id: "ick4",
    text: "Using baby talk in public",
    about: "chloe",
    added_by: "michael",
    created_at: "2026-03-09T00:00:00Z",
  },
  {
    id: "ick5",
    text: "Clapping when the plane lands",
    about: "chloe",
    added_by: "michael",
    created_at: "2026-03-07T00:00:00Z",
  },
];

export const MOCK_NIGHTMARES: Nightmare[] = [
  {
    id: "n1",
    text: "Michael ate steak (he's vegetarian)",
    about: "michael",
    added_by: "chloe",
    created_at: "2026-03-10T00:00:00Z",
  },
  {
    id: "n2",
    text: "Chloe forgot our anniversary",
    about: "chloe",
    added_by: "michael",
    created_at: "2026-03-08T00:00:00Z",
  },
  {
    id: "n3",
    text: "Michael moved to Mars without telling anyone",
    about: "michael",
    added_by: "michael",
    created_at: "2026-03-05T00:00:00Z",
  },
  {
    id: "n4",
    text: "Chloe became a morning person",
    about: "chloe",
    added_by: "chloe",
    created_at: "2026-03-03T00:00:00Z",
  },
];

export const MOCK_COLLAGE_PHOTOS: CollagePhoto[] = [
  {
    id: "cp1",
    url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200'%3E%3Cdefs%3E%3ClinearGradient id='g1' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3E%3Cstop offset='0%25' stop-color='%23ff9a9e'/%3E%3Cstop offset='100%25' stop-color='%23fad0c4'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='200' height='200' fill='url(%23g1)'/%3E%3C/svg%3E",
    caption: "Our first sunset call",
    added_by: "michael",
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "cp2",
    url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200'%3E%3Cdefs%3E%3ClinearGradient id='g2' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3E%3Cstop offset='0%25' stop-color='%23a18cd1'/%3E%3Cstop offset='100%25' stop-color='%23fbc2eb'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='200' height='200' fill='url(%23g2)'/%3E%3C/svg%3E",
    caption: "Matching outfits day",
    added_by: "chloe",
    created_at: "2026-03-05T00:00:00Z",
  },
  {
    id: "cp3",
    url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200'%3E%3Cdefs%3E%3ClinearGradient id='g3' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3E%3Cstop offset='0%25' stop-color='%23ffecd2'/%3E%3Cstop offset='100%25' stop-color='%23fcb69f'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='200' height='200' fill='url(%23g3)'/%3E%3C/svg%3E",
    caption: "Airport reunion",
    added_by: "michael",
    created_at: "2026-03-08T00:00:00Z",
  },
  {
    id: "cp4",
    url: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200'%3E%3Cdefs%3E%3ClinearGradient id='g4' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3E%3Cstop offset='0%25' stop-color='%2384fab0'/%3E%3Cstop offset='100%25' stop-color='%238fd3f4'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='200' height='200' fill='url(%23g4)'/%3E%3C/svg%3E",
    caption: "Late night FaceTime",
    added_by: "chloe",
    created_at: "2026-03-12T00:00:00Z",
  },
];

export const MOCK_ACTIVITY: Activity[] = [
  {
    id: "1",
    emoji: "🎙️",
    text: "Chloe sent a voice note",
    created_at: "2026-03-19T23:18:00Z",
    href: "/chat",
  },
  {
    id: "2",
    emoji: "📌",
    text: "Michael pinned a message",
    created_at: "2026-03-19T22:20:00Z",
    href: "/chat",
  },
  {
    id: "3",
    emoji: "🎬",
    text: "Chloe added \"Challengers\" to Recommendations",
    created_at: "2026-03-19T20:20:00Z",
    href: "/vault/recommendations",
  },
  {
    id: "4",
    emoji: "💭",
    text: "Michael added a new Topic",
    created_at: "2026-03-18T10:00:00Z",
    href: "/vault/topics",
  },
  {
    id: "5",
    emoji: "✨",
    text: "New moment: \"First road trip\"",
    created_at: "2026-03-17T15:00:00Z",
    href: "/vault/moments",
  },
];
